"""
FiLM-conditioned ResNet + CLIP text encoder for hierarchical skill embedding.

Architecture
------------
  Language path:
    subtask text -> CLIP text encoder [projection_dim=512] ->
      proj_a [d_action] -> s_a          (action type)
      proj_o [d_object] -> s_o          (object identity)
      film_mlp -> {(gamma_i, beta_i)} x 4  (FiLM conditioning per ResNet stage)

  Visual path:
    scene image -> ResNet-18 stem ->
      Stage1 -> FiLM(gamma_0, beta_0) ->
      Stage2 -> FiLM(gamma_1, beta_1) ->
      Stage3 -> FiLM(gamma_2, beta_2) ->
      Stage4 -> FiLM(gamma_3, beta_3) ->
      AvgPool [512] -> proj_c [d_context] -> s_c   (scene context)

FiLM (Feature-wise Linear Modulation): y = gamma * x + beta
  gamma, beta are per-channel vectors predicted from CLIP language features.
  This lets "the black bowl" steer the ResNet to attend to round/dark regions
  while "the drawer" steers it to attend to flat/rectangular regions --
  all from the same initial scene image.

Default inference (no training):
  FiLMGenerator is init with weight~0, gamma-bias=1, beta-bias=0, so FiLM
  defaults to identity and ResNet-18 uses pretrained ImageNet features.

After contrastive fine-tuning (build_contrastive_skill_emb.py --mode clip_film):
  FiLM learns to selectively modulate visual features via language.
"""

from __future__ import annotations

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as tv_models
import torchvision.transforms as T
from PIL import Image
from transformers import CLIPModel, CLIPProcessor


# ---------------------------------------------------------------------------
# Image pre-processing (standard ImageNet normalization for ResNet)
# ---------------------------------------------------------------------------

_IMAGENET_MEAN = [0.485, 0.456, 0.406]
_IMAGENET_STD  = [0.229, 0.224, 0.225]

_IMG_TRANSFORM = T.Compose([
    T.Resize(224),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize(mean=_IMAGENET_MEAN, std=_IMAGENET_STD),
])


def preprocess_image(img: np.ndarray) -> torch.Tensor:
    """Convert a (H, W, 3) uint8 numpy array to a (3, 224, 224) float tensor."""
    return _IMG_TRANSFORM(Image.fromarray(img.astype(np.uint8)))


def preprocess_images(imgs: list[np.ndarray]) -> torch.Tensor:
    """Batch-preprocess -> (N, 3, 224, 224)."""
    return torch.stack([preprocess_image(im) for im in imgs], dim=0)


# ---------------------------------------------------------------------------
# FiLM modules
# ---------------------------------------------------------------------------

class FiLMLayer(nn.Module):
    """Feature-wise Linear Modulation applied to spatial feature maps.

    y = gamma * x + beta
      x:     (B, C, H, W)
      gamma: (B, C)  -- channel-wise scale
      beta:  (B, C)  -- channel-wise shift
    """

    def forward(
        self,
        x:     torch.Tensor,
        gamma: torch.Tensor,
        beta:  torch.Tensor,
    ) -> torch.Tensor:
        c = x.shape[1]
        return gamma.view(-1, c, 1, 1) * x + beta.view(-1, c, 1, 1)


class FiLMGenerator(nn.Module):
    """Maps language features to per-stage FiLM parameters.

    One linear head per ResNet stage (4 heads for ResNet-18).
    Weight initialization: near-zero weights + bias set so gamma->1, beta->0,
    making FiLM default to identity -- pretrained ResNet features are
    preserved immediately out of the box before any training.
    """

    def __init__(self, lang_dim: int, stage_channels: list[int]):
        super().__init__()
        self.heads = nn.ModuleList()
        for c in stage_channels:
            head = nn.Linear(lang_dim, 2 * c)
            # Identity initialization
            nn.init.normal_(head.weight, std=0.01)   # small, near-zero
            nn.init.constant_(head.bias[:c], 1.0)    # gamma part -> 1
            nn.init.zeros_(head.bias[c:])             # beta part -> 0
            self.heads.append(head)

    def forward(
        self, lang_feat: torch.Tensor
    ) -> list[tuple[torch.Tensor, torch.Tensor]]:
        """Returns [(gamma_0,beta_0), ..., (gamma_3,beta_3)] per stage."""
        out = []
        for head in self.heads:
            ab = head(lang_feat)          # (B, 2C)
            c  = ab.shape[1] // 2
            out.append((ab[:, :c], ab[:, c:]))
        return out


# ---------------------------------------------------------------------------
# FiLM-conditioned ResNet-18
# ---------------------------------------------------------------------------

class FiLMResNet(nn.Module):
    """ResNet-18 with FiLM conditioning applied after each of the 4 stages.

    FiLM params are generated by a lightweight MLP from CLIP text features,
    so visual feature extraction is steered by the current subtask language.
    """

    _STAGE_CHANNELS = [64, 128, 256, 512]

    def __init__(self, lang_dim: int = 512, pretrained: bool = True):
        super().__init__()
        weights = (
            tv_models.ResNet18_Weights.IMAGENET1K_V1 if pretrained else None
        )
        base = tv_models.resnet18(weights=weights)

        # Stem: conv1 -> bn1 -> relu -> maxpool
        self.stem = nn.Sequential(
            base.conv1, base.bn1, base.relu, base.maxpool
        )
        # Four stages
        self.layer1 = base.layer1
        self.layer2 = base.layer2
        self.layer3 = base.layer3
        self.layer4 = base.layer4
        self.avgpool = base.avgpool   # AdaptiveAvgPool2d(1, 1)

        # FiLM modules
        self.film      = FiLMLayer()
        self.film_gen  = FiLMGenerator(lang_dim, self._STAGE_CHANNELS)

    def forward(
        self,
        img:       torch.Tensor,   # (B, 3, 224, 224)
        lang_feat: torch.Tensor,   # (B, lang_dim)
    ) -> torch.Tensor:             # (B, 512)
        params = self.film_gen(lang_feat)   # [(gamma,beta) x 4]

        x = self.stem(img)

        x = self.layer1(x)
        x = self.film(x, *params[0])   # stage-1 FiLM, ch=64

        x = self.layer2(x)
        x = self.film(x, *params[1])   # stage-2 FiLM, ch=128

        x = self.layer3(x)
        x = self.film(x, *params[2])   # stage-3 FiLM, ch=256

        x = self.layer4(x)
        x = self.film(x, *params[3])   # stage-4 FiLM, ch=512

        return self.avgpool(x).flatten(1)   # (B, 512)


# ---------------------------------------------------------------------------
# Full CLIPFiLMSkillEncoder
# ---------------------------------------------------------------------------

class CLIPFiLMSkillEncoder(nn.Module):
    """Multimodal skill encoder: CLIP text + FiLM-conditioned ResNet visual.

    Output: three disentangled, L2-normalised segments
      s_a  (d_action)  -- action type     from CLIP(verb phrase)
      s_o  (d_object)  -- object identity from CLIP(object phrase)
      s_c  (d_context) -- scene context   from FiLMResNet(image | full subtask)

    Total dim: d_action + d_object + d_context  (default 88)
    """

    def __init__(
        self,
        clip_model_name:   str  = "openai/clip-vit-base-patch32",
        d_action:          int  = 16,
        d_object:          int  = 40,
        d_context:         int  = 32,
        pretrained_resnet: bool = True,
        freeze_clip:       bool = True,
    ):
        super().__init__()

        # ---- CLIP ----
        self.clip_model = CLIPModel.from_pretrained(clip_model_name)
        self.clip_proc  = CLIPProcessor.from_pretrained(clip_model_name)
        if freeze_clip:
            for p in self.clip_model.parameters():
                p.requires_grad_(False)

        # Projected text feature dim (512 for ViT-B/32, 768 for ViT-L/14)
        clip_proj_dim = self.clip_model.config.projection_dim  # 512

        # ---- FiLM-ResNet for visual context ----
        self.film_resnet = FiLMResNet(
            lang_dim=clip_proj_dim, pretrained=pretrained_resnet
        )

        # ---- Projection heads ----
        self.proj_a = nn.Sequential(
            nn.Linear(clip_proj_dim, 64), nn.ReLU(),
            nn.Linear(64, d_action),
        )
        self.proj_o = nn.Sequential(
            nn.Linear(clip_proj_dim, 128), nn.ReLU(),
            nn.Linear(128, d_object),
        )
        self.proj_c = nn.Sequential(
            nn.Linear(512, 128), nn.ReLU(),
            nn.Linear(128, d_context),
        )

        self.d_action  = d_action
        self.d_object  = d_object
        self.d_context = d_context

    # ---- helpers ----

    def _encode_text(
        self, texts: list[str], device: torch.device | str
    ) -> torch.Tensor:
        """CLIP text encode -> (N, projection_dim), NOT L2-normalised yet."""
        toks = self.clip_proc(
            text=texts, return_tensors="pt", padding=True, truncation=True,
            max_length=77,
        )
        toks = {k: v.to(device) for k, v in toks.items()
                if isinstance(v, torch.Tensor)}
        # text_model returns BaseModelOutputWithPooling; apply text_projection
        text_out = self.clip_model.text_model(**toks)
        feats = self.clip_model.text_projection(text_out.pooler_output)  # (N, 512)
        return feats   # raw (unnormalised) projected features

    # ---- forward (tensor API) ----

    def forward(
        self,
        action_texts: list[str],     # verb phrases
        object_texts: list[str],     # object phrases
        full_texts:   list[str],     # complete subtask strings (for FiLM)
        images:       torch.Tensor,  # (B, 3, 224, 224)
    ) -> dict[str, torch.Tensor]:
        device = images.device

        a_feat = self._encode_text(action_texts, device)   # (B, 512)
        o_feat = self._encode_text(object_texts, device)   # (B, 512)
        f_feat = self._encode_text(full_texts,   device)   # (B, 512) for FiLM

        vis_feat = self.film_resnet(images, f_feat)        # (B, 512)

        s_a = F.normalize(self.proj_a(a_feat),   dim=-1)  # (B, d_action)
        s_o = F.normalize(self.proj_o(o_feat),   dim=-1)  # (B, d_object)
        s_c = F.normalize(self.proj_c(vis_feat), dim=-1)  # (B, d_context)

        return {"s_a": s_a, "s_o": s_o, "s_c": s_c}

    # ---- convenience numpy wrapper ----

    @torch.inference_mode()
    def forward_numpy(
        self,
        action_texts: list[str],
        object_texts: list[str],
        full_texts:   list[str],
        images:       list[np.ndarray],   # (H, W, 3) uint8
        device:       str = "cuda",
    ) -> dict[str, np.ndarray]:
        imgs_t = preprocess_images(images).to(device)
        out = self.forward(action_texts, object_texts, full_texts, imgs_t)
        return {k: v.cpu().numpy().astype(np.float32) for k, v in out.items()}
